version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  reverseproxy:
    image: nginx
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./MicroServices/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "glitchtip.kmp.com:127.0.0.1"
    restart: always

  dispatcher:
    container_name: dispatcher
    build:
      context: .
      dockerfile: ./MicroServices/DispatchService/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
      - ./MicroServices_Common:/app/_Common
    environment:
      - MQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - rabbitmq

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./MicroServices/AdminService/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
      - ./MicroServices_Common:/app/_Common
    environment:
      - MQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - rabbitmq
  bdd:
    container_name: bdd
    build:
      context: .
      dockerfile: ./MicroServices/BddService/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
      - ./MicroServices/_Common:/app/_Common
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - reverseproxy

  bid:
    container_name: bid
    build:
      context: .
      dockerfile: ./MicroServices/BidService/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
      - ./MicroServices/_Common:/app/_Common
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - reverseproxy

  message:
    container_name: test
    build:
      context: .
      dockerfile: ./MicroServices/MessageService/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
      - ./MicroServices/_Common:/app/_Common
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - reverseproxy

  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  pg-data:

networks:
  default:
    name: glitchtip
