version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  reverseproxy:
    image: nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "glitchtip.kmp.com:127.0.0.1"
    restart: always

  dispatcher:
    container_name: dispatcher
    build:
      context: .
      dockerfile: ./DispatchService/Dockerfile
    volumes:
      - ../node_modules:/app/node_modules
      - ./_Common:/app/_Common
    environment:
      - MQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - rabbitmq

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./AdminService/Dockerfile
    volumes:
      - ../node_modules:/app/node_modules
      - ./_Common:/app/_Common
    environment:
      - MQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - rabbitmq

  bid:
    container_name: bid
    build:
      context: .
      dockerfile: ./BidService/Dockerfile
    volumes:
      - ../node_modules:/app/node_modules
      - ./_Common:/app/_Common
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - reverseproxy

  message:
    container_name: test
    build:
      context: .
      dockerfile: ./MessageService/Dockerfile
    volumes:
      - ../node_modules:/app/node_modules
      - ./_Common:/app/_Common
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
      - reverseproxy

  db:
    container_name: db
    image: mongo
    ports:
      - "27020:27017"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
volumes:
  pg-data:

networks:
  default:
    name: glitchtip